--Q7문제풀이
--EMPLOYEES 테이블에서 SALARY가 8000이상인 직원의 수를 조회
SELECT COUNT(SALARY)
FROM EMPLOYEES
WHERE SALARY>=8000;

--EMPLOYEES테이블에서 HIRE_DATE가 2007년 1월 1일 이후인 직원의 수를 조회
SELECT COUNT(HIRE_DATE)
FROM EMPLOYEES
WHERE HIRE_DATE > '20070101';

--JOBS 테이블에서 MAX_SALARY 값의 합계와 평균을 조회
SELECT SUM(MAX_SALARY) AS SUM , AVG(MAX_SALARY) AS AVG
FROM JOBS;

--EMPLOYEES 테이블에서 JOB_ID가 'IT_PROG'인 직원의 SALARY합계와 평균을 조회
SELECT SUM (SALARY), AVG (SALARY)
FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG';

DESC EMPLOYEES;

--EMPLOYEES 테이블에서 DEPARTMENT_ID가 50과 80 사이인 직원의 FIRST_NAME,
--SALARY, 그리고 COMMISSION_PCT의 평균값을 FIRST_NAME 정렬 기준으로 조회
--(NULL 값은 0으로 출력)
SELECT FIRST_NAME, SALARY, AVG(NVL(COMMISSION_PCT,0)) OVER (ORDER BY FIRST_NAME)
FROM EMPLOYEES
WHERE DEPARTMENT_ID BETWEEN 50 AND 80;
--ORDER BY FIRST_NAME;

-----------------------------------------------------------------------------

--JOBS테이블에서 MAX_SALARY 값의 최솟값과 MAX_SALARY 값의 최댓값을 조회
SELECT MAX(MAX_SALARY), MIN(MAX_SALARY)
FROM JOBS;

--JOBS 테이블에서 JOB_TITLE이 'PROGRAMMER'인 직업의 MAX_SALARY
--값의 최솟값과 MAX_SALARY 값의 최댓값을 조회
SELECT MAX(MAX_SALARY), MIN(MAX_SALARY)
FROM JOBS
WHERE JOB_TITLE = 'Programmer';

--EMPLOYEES 테이블에서 DEPARTMENT_ID가 50인 데이터의 HIRE_DATE 최소값과 최댓값 조회
SELECT MAX(HIRE_DATE) AS 최대값 , MIN(HIRE_DATE) AS 최소값
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50;

--EMPLOYEES 테이블에서 DEPARTMENT_ID 100인 데이터의 FIRST_NAME, SALAY 그리고 
--SALARY의 (VARIANCE(salary)분산값)을 HITE_DATE 정렬 기준으로 조회
SELECT FIRST_NAME, SALARY, VARIANCE(salary) OVER (ORDER BY hire_date)
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 100;

--EMPLOYEES테이블에서 HIRE_DATE 값이 2004년 1월 1일부터 2006년 12월 31일 사이의 테이터를
--JOB_ID 기준으로 그룹화한 뒤에 JOB_ID와 SALARY 최솟값과 최대값을 조회

SELECT JOB_ID , MAX(salary),MIN(salary)
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '20040101' AND '20061231'
GROUP BY JOB_ID
ORDER BY JOB_ID;

--EMPLOYEES 테이블에서 DEPARTMENT_ID가 50과 80인 데이터를 DEPARTMENT_ID와
--JOB_ID 기준으로 그룹화한 뒤에 (((DEPERTMENT_ID와 JOB_ID, SALATY 합계, 최솟값, 최대값을
--JOB_ID 기준으로 정렬)))하여 조회
SELECT DEPARTMENT_ID , JOB_ID, SUM(salary), MAX(salary),MIN(salary)
FROM employees
WHERE DEPARTMENT_ID IN (50,80)
GROUP BY DEPARTMENT_ID, JOB_ID
ORDER BY JOB_ID;

--EMPLOYEES 테이블에서 DEPARTMENT_ID 와 JOB_ID 기준으로  (((그룹화한 뒤에 SALARY
--평균값이 12000 이상인 데이터만)))) DEPARTMENT_ID와 JOB_ID, 
--SALAY 최솟값, 최대값, 평균을 DEPARTMENT_ID 기준으로 정렬하여 조회

-- AVG(SALARY) 그룹함수는 WHERE절 사용불가
SELECT DEPARTMENT_ID, JOB_ID, MIN(SALARY), MAX(salary), AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, JOB_ID
HAVING AVG(SALARY) >= 12000
ORDER BY DEPARTMENT_ID;
